# Generated by Django 5.2.8 on 2025-11-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(choices=[('1', 'ROJO'), ('2', 'AZUL'), ('3', 'VERDE')], max_length=1, verbose_name='color'),
        ),
    ]
